apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-app-deployment
  labels:
    app: car_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car_app
  template:
    metadata:
      labels:
        app: car_app
    spec:
      containers:
      - name: car-app
        image: replace
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: car-app-service
spec:
  selector:
    app: car_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
